default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  host: localhost
  database: runa_api_development

test:
  <<: *default
  host: localhost
  database: runa_api_test

production:
  <<: *default
  database: runa_api_production
